# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
templates:
  params:
    author-email: dan.lucsanszky@gmail.com
    author-name: Daniel Lucsanszky
    copyright: Daniel Lucsanszky
    github-username: Lucsanszky
